### ISSUE TITLE
Per project configuration

### ISSUE THREAD

**Issue by smebberson** [almahdi-chihaoui/watchkube#1]
watchkube looks pretty cool. Have you been using it much? How does it perform with lots of files?

I haven't actually tried it out myself yet. If we were to adopt it, we'd probably need some kind of configuration per _project_. Something we could check into source control

Have you considered bringing the configurations (`./src/data/data/data.json`) up into the main directory. Maybe a `.watchkube.json` file or something similar?

**Comment by almahdi-chihaoui** [comment]
Hi,
I've been using it for almost 3 months in my development environment in a heavy project and it does what it is supposed to do. It can perform well with lots of files but it depends on your machine specs if your are using local kubernetes cluster (minikube) or your network speed if your using kubernetes from a cloud service provider, but I wouldn't recommend it, maybe with a small git checkouts that touches few files, but with hundreds or thousands of files, that's hundreds or thousands of kubectl commands which can stall the machine.
For the data.json file, I actually considered moving it, it was going to be my next step to move it outside the module folder, I am thinking about putting it under the home folder (~/.watchkube/data.json) to prevent it from being erased during updates, but unfortunately, I've ben very busy in the last couple of months.
Regards.

**Comment by smebberson** [comment]
@almahdi-chihaoui, that wouldn't allow the configuration to be checked in to git. Is that something you'd consider incorporating?

**Comment by almahdi-chihaoui** [comment]
@smebberson , yes, actually the data.json file is used as a local database, it doesn't need to be checked in git, it is used so that the user can store his configurations (his project's paths, ignored paths ..).
The only thing that needs to be done is that watchkube need to check if there is a file data.json under ~/.watchkube folder after its installation, if there one, it use it, otherwise it create a new one.

**Comment by smebberson** [comment]
Okay, but that doesn't really work in a team, per project. For example, I might set it up, have everything stored with the project in git, then write some notes. My team mate will come along, follow the notes and have watchkube up and running in no time, without having to set any configuration or anything.

Does that help explain what I'm after, and why I think having it in Git is important? At the moment, with it being stored in ~/.watchkube, it can't be shared.

Also, per project is important I think. Different projects might have different watches and therefore the ability to just checkout a project with Git and having it all running quickly and easily is important.

What do you think?

**Comment by almahdi-chihaoui** [comment]
Hi,
Well here we are talking about a new feature, and i really thought about it, to make watchkube able to import or apply configs from a file (json or yaml ...), in that case, a team can share a config file in in the project's repo, it is a cool idea.
I will be soon working on it.

**Comment by smebberson** [comment]
Yeah, it is a new feature... for sure. Does watchkube have to import or apply configs though? That seems like an unnecessary overhead. Can't it just directly use different files as required?

Many systems look at a particular place for a config file, but can be directed to another as required (via a command line flag or something similar). I can give many examples if you need more persuasion...

**Comment by almahdi-chihaoui** [comment]
Ah, i see, that's even a better idea. So basically, when we start watchkube, it needs to look for a specific config file (exp: watchkubeconfig.json/yaml) in the current directory by default or other directory if it is specified, if that file was found, it uses it, otherwise, it uses its local file. cool.
I already started working on the import feature, it is almost done. I will start working on your idea (it won't take much).
Hopefully, all those features will be available in the next version.
Thanks.

**Comment by smebberson** [comment]
Yeah, that sounds awesome. Is there anything I can do to help out?

**Comment by almahdi-chihaoui** [comment]
Hi, 
Sorry for my late response, the import feature is done, also the per project config file is done (not tested yet).
The only thing left is to move the local data.json file out of the module folder (to ~/.watchkube for exp).
What do you think? should we add it?

**Comment by smebberson** [comment]
No worries at all. Awesome news, anything I can do to help test?

Yeah, I think definitely move it to ~/.watchkube. If you look at a large number of the other modules out there (including NPM with `~/.npm/` and `~/.npmrc`), none of them store their config in the module folder. The module folder gets wiped and restored all the time so I don't really think it's a safe place.

**Comment by almahdi-chihaoui** [comment]
Good,
Yes please, testing it would be appreciated.
Thanks :)

**Comment by smebberson** [comment]
Sure thing, is it on `master`?

**Comment by almahdi-chihaoui** [comment]
Yes, everything is on master :)

**Comment by almahdi-chihaoui** [comment]
Hi,
Everything is done now, i just released a new version (1.2.0), and it is published.

Thanks.
